"""adding child relationship to blogposts

Revision ID: edaf69e23e77
Revises: 69dabe847364
Create Date: 2025-06-16 19:01:24.825126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaf69e23e77'
down_revision = '69dabe847364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_parent_post_id', 'blog_posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_parent_post_id', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
